checkly/theheadless.dev

blog/.vuepress/config.js
=> feat: default meta image

blog/posts/basics-clicking-typing.md, blog/posts/basics-local-setup.md, blog/posts/basics-navigation.md, blog/posts/basics-playwright-intro.md, blog/posts/basics-puppeteer-intro.md, blog/posts/basics-selectors.md, blog/posts/challenging-flows.md, blog/posts/e2e-account-settings.md, blog/posts/e2e-checkout.md, blog/posts/e2e-coupon.md, blog/posts/e2e-login.md, blog/posts/e2e-search.md, blog/posts/e2e-signup.md, blog/posts/google-login.md, blog/posts/microsoft-live-login.md, blog/posts/test-data-intro.md, blog/posts/valuable-tests.md
Use lower case tags for better static site generation.
=> chore: use lower case for tags generation

blog/.vuepress/config.js
=> chore: enable tips/danger/warning custom blocks

blog/.vuepress/theme/styles/index.styl
=> chore: font load correct weights

blog/.vuepress/theme/components/Footer.vue, blog/.vuepress/theme/components/Home.vue, blog/.vuepress/theme/layouts/Layout.vue, blog/.vuepress/theme/layouts/Post.vue
=> chore: aesthetics

blog/.vuepress/config.js, blog/.vuepress/theme/components/Footer.vue, blog/posts/basics-clicking-typing.md, blog/posts/basics-local-setup.md, blog/posts/basics-navigation.md, blog/posts/basics-playwright-intro.md, blog/posts/basics-puppeteer-intro.md, blog/posts/basics-selectors.md, blog/posts/challenging-flows.md, blog/posts/e2e-account-settings.md, blog/posts/e2e-checkout.md, blog/posts/e2e-coupon.md, blog/posts/e2e-login.md, blog/posts/e2e-search.md, blog/posts/e2e-signup.md, blog/posts/google-login.md, blog/posts/microsoft-live-login.md, blog/posts/test-data-intro.md, blog/posts/valuable-tests.md
=> Copy updates ch000

blog/.vuepress/theme/components/AlgoliaSearchBox.vue
=> chore: algolia styles

blog/.vuepress/theme/components/Home.vue, blog/.vuepress/theme/components/Navbar.vue
=> fix: safari mobile

blog/.vuepress/theme/components/Home.vue, blog/.vuepress/theme/components/PostMeta.vue, blog/.vuepress/theme/layouts/Layout.vue, blog/posts/basics-clicking-typing.md, package-lock.json, package.json
=> feat: posts multiple contributors

blog/.vuepress/theme/components/Home.vue
=> fix: mobile subscribe button font-size

blog/.vuepress/theme/components/Contributors.vue, blog/.vuepress/theme/components/Home.vue
=> feat: show contributors

blog/.vuepress/config.js, blog/.vuepress/theme/components/Home.vue
=> feat: home page add learn more links

blog/.vuepress/config.js, blog/.vuepress/theme/layouts/GlobalLayout.vue, package-lock.json, package.json
=> feat: cookies banner

blog/.vuepress/theme/components/Home.vue
=> fix: recent guides order latests

blog/.vuepress/theme/components/Footer.vue, blog/.vuepress/theme/components/Home.vue
- Increase footer text `line-height`
- Recent guides stick contributor to the bottom
=> chore: css tweaks

blog/.vuepress/config.js
=> fix: rss feed order by date

blog/posts/e2e-file-download.md, blog/posts/e2e-invoice-download.md, blog/snippets/playwright/file-download-alt.js, blog/snippets/playwright/file-download.js, blog/snippets/puppeteer/file-download.js
@tnolet maybe you know more about file downloads with PPTR and can verify whether I missed a better way of doing things (looking at the second, alternate version of the download flow in this guide).
=> E2e download file

blog/.vuepress/config.js, blog/.vuepress/theme/layouts/GlobalLayout.vue, package-lock.json, package.json
=> Delete Google Analytics

blog/.vuepress/theme/components/Footer.vue, blog/.vuepress/theme/components/PostEdit.vue, blog/.vuepress/theme/components/PostMeta.vue, blog/.vuepress/theme/components/SidebarLink.vue
=> chore: update text color for better contrast

blog/posts/basics-clicking-typing.md, blog/posts/basics-navigation.md, blog/posts/basics-performance.md, blog/posts/basics-scraping.md, blog/posts/basics-selectors.md, blog/posts/basics-taking-screenshots.md, blog/posts/challenging-flows.md, blog/posts/e2e-account-settings.md, blog/posts/e2e-checkout.md, blog/posts/e2e-coupon.md, blog/posts/e2e-file-download.md, blog/posts/e2e-login.md, blog/posts/e2e-search.md, blog/posts/e2e-signup.md, blog/posts/generating-pdfs.md, blog/posts/google-login.md, blog/posts/managing-cookies.md, blog/posts/microsoft-live-login.md, blog/posts/request-interception.md, blog/posts/script-recorders.md, blog/posts/test-data-intro.md, blog/posts/valuable-tests.md
I am adding subtitle to all existing articles. After this we should probably merge https://github.com/checkly/theheadless.dev/pull/106, right?
=> refactor: add subtitle

blog/.vuepress/config.js, blog/.vuepress/theme/layouts/Post.vue, package-lock.json, package.json
Please review. I selected the obvious social networks. The extension supports more...
=> add social share

blog/.vuepress/theme/components/ChecklyNavbar.vue, blog/.vuepress/theme/components/Navbar.vue, blog/.vuepress/theme/layouts/GlobalLayout.vue, blog/.vuepress/theme/layouts/Layout.vue, blog/.vuepress/theme/layouts/Post.vue
=> feat: add ChecklyNavbar everywhere

blog/posts/request-interception.md, blog/snippets/playwright/response-interception.js
- Add Playwright portion for stubbing requests
- Add response-interception example
=> post: Add Playwright stub to network article
